# Implicit System Requirements:
# - bear


[project]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "python"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[tasks]
nsys-prof = { cmd = "nsys profile -o out/profile", cwd ="test-mitsuba", depends-on =["build-mitsuba"] }
profile = { cmd = "perf record -o out/perf.data --call-graph dwarf -e cycles -m 8M --aio -z --sample-cpu", cwd = "test-mitsuba", depends-on = [
    "build-mitsuba",
] }
# Mitsuba GCC
sanitize-mitsuba = { cmd = "echo $PYTHONPATH && compute-sanitizer python -m pytest", cwd = "mitsuba3/build-mitsuba", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba",
] }
test-mitsuba = { cmd = "echo $PYTHONPATH && python -m pytest", cwd = "mitsuba3/build-mitsuba", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba",
] }
profile-mitsuba = { cmd = "perf record -o perf.data --call-graph dwarf -e cycles -m 8M --aio -z --sample-cpu python -m pytest", cwd = "mitsuba3/build-mitsuba", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba",
] }
hotspot-mitsuba = { cmd = "hotspot perf.data", cwd = "mitsuba3/build-mitsuba"}
debug-mitsuba = { cmd = "echo $PYTHONPATH && gdb --args python -m pytest", cwd = "mitsuba3/build-mitsuba", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba",
] }
build-mitsuba = { cmd = "ninja", cwd = "mitsuba3/build-mitsuba", env = { LD_LIBRARY_PATH = "$CONDA_PREFIX/lib" }, depends-on = [
    "configure-mitsuba",
] }
configure-mitsuba = { cmd = "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja -S mitsuba3/ -B mitsuba3/build-mitsuba" }

# Mitsuba Clang
test-mitsuba-clang = { cmd = "echo $PYTHONPATH && python -m pytest", cwd = "mitsuba3/build-mitsuba-clang", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba-clang",
] }
debug-mitsuba-clang = { cmd = "echo $PYTHONPATH && gdb --args python -m pytest", cwd = "mitsuba3/build-mitsuba-clang", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba-clang",
] }
build-mitsuba-clang = { cmd = "ninja", cwd = "mitsuba3/build-mitsuba-clang", depends-on = [
    "configure-mitsuba-clang",
], env = { LIBRARY_PATH = "$CONDA_PREFIX/lib" } }
configure-mitsuba-clang = { cmd = "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS='-fuse-ld=lld' -G Ninja -S mitsuba3/ -B mitsuba3/build-mitsuba-clang", env = { CC = "clang", CXX = "clang++", LD_LIBRARY_PATH = "$CONDA_PREFIX/lib", LIBRARY_PATH = "$CONDA_PREFIX/lib" } }

# Dr.Jit GCC
test-drjit = { cmd = "python -m pytest", cwd = "mitsuba3/build-drjit", depends-on = [
    "build-drjit",
] }
debug-drjit = { cmd = "gdb --args python -m pytest", cwd = "mitsuba3/build-drjit", depends-on = [
    "build-drjit",
] }
build-drjit = { cmd = "ninja", cwd = "mitsuba3/build-drjit", depends-on = [
    "configure-drjit",
] }
configure-drjit = { cmd = "cmake -DDRJIT_ENABLE_TESTS=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja -S mitsuba3/ext/drjit/ -B mitsuba3/build-drjit" }

# Dr.Jit Clang
test-drjit-clang = { cmd = "python -m pytest", cwd = "mitsuba3/build-drjit-clang", depends-on = [
    "build-drjit-clang",
] }
debug-drjit-clang = { cmd = "gdb --args python -m pytest", cwd = "mitsuba3/build-drjit-clang", depends-on = [
    "build-drjit-clang",
] }
build-drjit-clang = { cmd = "ninja", cwd = "mitsuba3/build-drjit-clang", depends-on = [
    "configure-drjit-clang",
], env = { LIBRARY_PATH = "$CONDA_PREFIX/lib" } }
configure-drjit-clang = { cmd = "cmake -DDRJIT_ENABLE_TESTS=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja -S mitsuba3/ext/drjit/ -B mitsuba3/build-drjit-clang", env = { CC = "clang", CXX = "clang++", LD_LIBRARY_PATH = "$CONDA_PREFIX/lib", LIBRARY_PATH = "$CONDA_PREFIX/lib" } }


# Dr.Jit core GCC
build-drjit-core = { cmd = "ninja", cwd = "mitsuba3/build-drjit-core", depends-on = [
    "configure-drjit-core",
] }
configure-drjit-core = { cmd = "cmake -DDRJIT_CORE_ENABLE_TESTS=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja -S mitsuba3/ext/drjit/ext/drjit-core -B mitsuba3/build-drjit-core" }

[dependencies]
cmake = "3.28.*"
gcc = "13.2.*"
gxx = "13.2.*"
python = "3.11.*"
zlib = "==1.3.1"
pkg-config = ">=0.29.2,<0.30"
clang = ">=19.1.1,<20"
clangxx = ">=19.1.1,<20"
embree = ">=4.3.3,<5"
libcxx = ">=19.1.1,<20"
libcxx-devel = ">=19.1.1,<20"
libcxxabi = ">=19.1.1,<20"
ninja = ">=1.12.1,<2"
llvmdev = ">=19.1.4,<20"
lld = ">=19.1.4,<20"
mold = ">=2.35.1,<3"

pytest = ">=8.3.3,<9"
numpy = ">=2.1.2,<3"
tqdm = ">=4.67.1,<5"

cuda = "*"
ccache = ">=4.10.1,<5"

[target.linux-64.activation]
scripts = ["mitsuba3/build-mitsuba/setpath.sh"]

[target.linux-64.activation.env]
CMAKE_CXX_COMPILER_LAUNCHER="ccache"
CMAKE_PREFIX_PATH = "$CONDA_PREFIX"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"
CUDA_TOOLKIT_ROOT_DIR = "$CONDA_PREFIX/lib"
# PYTHONPATH = "python:$PYTHONPATH"
